#!/bin/bash

export GITHUB_ACTION_PATH=$(pwd)
export SIMULATED_GITHUB_ACTION_CONTEXT="${GITHUB_ACTION_PATH}/.gradle-metadata-action"

export RUNNER_TEMP="${SIMULATED_GITHUB_ACTION_CONTEXT}/tmp"
export GITHUB_ENV="${SIMULATED_GITHUB_ACTION_CONTEXT}/GITHUB_ENV"
export GITHUB_OUTPUT="${SIMULATED_GITHUB_ACTION_CONTEXT}/GITHUB_OUTPUT"

rm -rf "$SIMULATED_GITHUB_ACTION_CONTEXT"
mkdir -p "$SIMULATED_GITHUB_ACTION_CONTEXT" "$RUNNER_TEMP"
touch "$GITHUB_ENV" "$GITHUB_OUTPUT"

export GRADLE_METADATA_ACTION_CONTEXT=test
export GRADLE_METADATA_ACTION_VERSION=1.0.0

./gradle-metadata-action.sh
