name: test

on:
  push:
    branches:
      - 'main'
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Gradle meta
        id: meta
        uses: ./
        with:
          context: "test"
          version: "1.0.0-SNAPSHOT"

      - name: Inspect "name" output
        run: echo "${{ steps.meta.outputs.name }}"

      - name: Inspect "version" output
        run: echo "${{ steps.meta.outputs.version }}"

      - name: Inspect "source-compatibility" output
        run: echo "${{ steps.meta.outputs.source-compatibility }}"

      - name: Inspect "target-compatibility" output
        run: echo "${{ steps.meta.outputs.target-compatibility }}"

      - name: Inspect "bake-file" output
        run: echo "${{ steps.meta.outputs.bake-file }}"

      - name: Validate bake file
        run: docker buildx bake -f "${{ steps.meta.outputs.bake-file }}" --print gradle-metadata-action
